import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BackgroundCanvas from '../components/home/BackgroundCanvas'

import { debounce } from '../util/index'

interface Size {
  width: number;
  height: number;
}

const Home: NextPage = () => {
  const [screenSize, setScreenSize] = useState<Size>({width: 0, height: 0})
  useEffect(() => {
    const resize = () => {
      setScreenSize({ width: window.innerWidth, height: window.innerHeight })
    }
    resize()
    window.addEventListener('resize', debounce(resize))
    return () => {
      window.removeEventListener('resize', resize)
    }
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.background}>
          <BackgroundCanvas
            className={styles.canvasBackground}
            canvasSize={screenSize}
          />
        </div>
      </main>
    </div>
  )
}

export default Home
